# Generated by Django 3.2.16 on 2023-01-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_background_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background_video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='background_video',
            name='vedio_file',
            field=models.FileField(blank=True, null=True, upload_to='Header_Vedios', verbose_name='Home page Background video'),
        ),
    ]
