# Generated by Django 3.2.16 on 2023-01-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0003_auto_20230109_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background_video',
            name='vedio_file',
        ),
        migrations.AddField(
            model_name='background_video',
            name='video_url',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Home page Background video'),
        ),
    ]
